//converted from  thtml1.html  getsize= 2624
const char* _thtml1_html_={\
  "<!DOCTYPE HTML>\n"
  "<html>\n"
  "<META name='viewport' content='width=device-width, initial-scale=1'>\n"
        "<title>Termostat</title>\n"
  "<SCRIPT>\n"
  "xmlHttp=createXmlHttpObject();\n"
""
  "function createXmlHttpObject(){\n"
    "if(window.XMLHttpRequest){\n"
      "xmlHttp=new XMLHttpRequest();\n"
    "}else{\n"
      "xmlHttp=new ActiveXObject('Microsoft.XMLHTTP');\n"
    "}\n"
    "return xmlHttp;\n"
  "}\n"
  ""
  "function process(){\n"
    "if(xmlHttp.readyState==0||xmlHttp.readyState==4){\n"
      "xmlHttp.onreadystatechange=function(){\n"
        "if(xmlHttp.readyState==4&&xmlHttp.status==200){\n"
          "xmlDoc=xmlHttp.responseXML;\n"
          "xmlmsg=xmlDoc.getElementsByTagName('millistime')[0].firstChild.nodeValue;\n"
          "document.getElementById('runtime').innerHTML=xmlmsg;\n"
          "xmlmsg=xmlDoc.getElementsByTagName('sliderval0')[0].firstChild.nodeValue;\n"
          "document.getElementById('slider0').value=xmlmsg;\n"
          "document.getElementById('Sliderval0').innerHTML=xmlmsg;\n"
          "xmlmsg=xmlDoc.getElementsByTagName('ESPval0')[0].firstChild.nodeValue;\n"
          "document.getElementById('ESPval0').innerHTML=xmlmsg;\n"
        "}\n"
      "}\n"
      "xmlHttp.open('PUT','xml',true);\n"
      "xmlHttp.send(null);\n"
    "}\n"
    "setTimeout('process()',1000);\n"
  "}\n"
""
  "function Slider(cnt){\n"
    "sliderVal=document.getElementById('slider'+cnt).value;\n"
    "document.getElementById('Sliderval'+cnt).innerHTML=sliderVal;\n"
    "document.getElementById('ESPval'+cnt).innerHTML=9*(100-sliderVal)+100;\n"
    "if(xmlHttp.readyState==0||xmlHttp.readyState==4){\n"
      "xmlHttp.open('PUT','setESPval?cnt='+cnt+'&val='+sliderVal,true);\n"
      "xmlHttp.send(null);\n"
    "}\n"
  "}\n"
""
  "</SCRIPT>\n"
""
  "<BODY onload='process()'>\n"
  "<BR>Change slider0 to control LED blink...<BR>\n"
  "Runtime = <A ID='runtime'></A><BR><BR>\n"
  "<TABLE BORDER=1 style='text-align:center;border-collapse:collapse'>\n"
    "<TR>\n"
    "<TD><BR><INPUT ID='slider0' TYPE='range' ONCHANGE='Slider(0)'></TD>\n"
    "<TD>Slidervalue0= <A ID='Sliderval0'></A><BR>\n"
    "ESPval0 = <A ID='ESPval0'></A> milliseconds</TD>\n"
    "</TR>\n"
  "</TABLE>\n"
"<form id=\"check_LEDs\" name=\"LED_form\">\n"
"<input type=\"checkbox\" name=\"chk_group[]\" value=\"value1\" />Value 1<br />\n"
"<input type=\"checkbox\" name=\"chk_group[]\" value=\"value2\" />Value 2<br />\n"
"<input type=\"checkbox\" name=\"chk_group[]\" value=\"value3\" />Value 3<br />\n"
"</form>\n"
"<form action=\"/wifi\" method=\"get\"><button>Configure WiFi</button></form><br/>\n"
"<form action=\"/0wifi\" method=\"get\"><button>Configure WiFi (No Scan)</button></form><br/>\n"
"<form action=\"/i\" method=\"get\"><button>Info</button></form><br/>\n"
"<form action=\"/r\" method=\"post\"><button>Reset</button></form>\n"
  "</BODY>\n"
  "</HTML>\n"};
// End thtml1.html writedsz 2624
